version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
# define a job to be invoked later in a workflow.
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "14.15.1"
      - checkout
      # setup aws cli
      - aws-cli/setup
      # setup eb cli
      - eb/setup
        # install frontend dependencies
      - run:
          name: Front-End Install
          command: |
            npm run front-end:install
        # install backend dependencies
      - run:
          name: Back-End Install
          command: |
            npm run back-end:install
        # build frontend
      - run:
          name: Front-End Build
          command: |
            npm run front-end:build
        # build backend
      - run:
          name: Back-End Build
          command: |
            npm run back-end:build
        # deploy frontend
      - run:
          name: Deploy UI
          command: |
            npm run front-end:deploy
        # deploy backend
      - run:
          name: Deploy Server
          command: |
            npm run back-end:deploy
# start the workflows
workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
